// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDniqw7uaYPbgmFlcGZSybTdaQ0ckVXlIw',
    appId: '1:987977647911:web:7e56f1cf5e464d455a0b02',
    messagingSenderId: '987977647911',
    projectId: 'whatsapp-status-saver-716c1',
    authDomain: 'whatsapp-status-saver-716c1.firebaseapp.com',
    storageBucket: 'whatsapp-status-saver-716c1.appspot.com',
    measurementId: 'G-169C1207LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsoyyK8Hh0oTvooYzZwCo-4MqWWFhzqOw',
    appId: '1:987977647911:android:fe6ef8dce43edb005a0b02',
    messagingSenderId: '987977647911',
    projectId: 'whatsapp-status-saver-716c1',
    storageBucket: 'whatsapp-status-saver-716c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPo7flNtavY0dKk1nyX3bHDv3jN44aOK4',
    appId: '1:987977647911:ios:9636c0bf698f85de5a0b02',
    messagingSenderId: '987977647911',
    projectId: 'whatsapp-status-saver-716c1',
    storageBucket: 'whatsapp-status-saver-716c1.appspot.com',
    iosClientId: '987977647911-38ribgt48tbfo1maaqagpi4ukm4gpnvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPo7flNtavY0dKk1nyX3bHDv3jN44aOK4',
    appId: '1:987977647911:ios:9636c0bf698f85de5a0b02',
    messagingSenderId: '987977647911',
    projectId: 'whatsapp-status-saver-716c1',
    storageBucket: 'whatsapp-status-saver-716c1.appspot.com',
    iosClientId: '987977647911-38ribgt48tbfo1maaqagpi4ukm4gpnvs.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterApplication1',
  );
}
